# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  purchaseorders-app:
    image: purchaseorders
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.30.12.126:5432/iss_purchase
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://172.30.12.126:5432/iss_purchase
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    volumes:
      - purchase_orders:/app/fileupload
    working_dir: /app
volumes:
  purchase_orders:
    external: true

